baseURL = "https//barkhan.com.au/"
canonifyURLs = false
languageCode = "en-us"
title = "Jerome Barkhan"
theme = "paper"
enableInlineShortcodes = true
enableMath = true

[params]
  color = "light"
  github = "jbarkhan"
  linkedin = "jeromebarkhan"
  name = "Notes"
  bio = "A personal blog about cybersecurity and sometimes other things."

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

 