baseURL = "https//nullthought.dev/"
canonifyURLs = false
languageCode = "en-us"
title = "null thought"
theme = "paper"
enableInlineShortcodes = true
enableMath = true

[params]
  color = "linen"
  github = "jbarkhan"
  linkedin = "jeromebarkhan"
  name = "notes"
  bio = "A personal blog about cyber security and maybe some other things. I am using this space to think my thoughts through writing and I hope that you can find something useful in the process. Some of my thoughts may even be good ones, but I encourage you to apply your own judgement."
  monoDarkIcon = true
  math = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = 'home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = "whoami"
    url = "/whoami/"
    weight = 20
 