baseURL = "https//barkhan.com.au/"
canonifyURLs = false
languageCode = "en-us"
title = "Jerome Barkhan"
theme = "paper"
enableInlineShortcodes = true
enableMath = true

[params]
  color = "light"
  github = "jbarkhan"
  linkedin = "jeromebarkhan"
  name = "Notes"
  bio = "A personal blog about cyber security and maybe other things. I am new to the field and lack both the experience and knowledge to contribute as an expert. Rather, I plan to use this space for now to think my thoughts through writing and hope that you can take something beneficial from that."

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = 'home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = "whoami"
    url = "/whoami/"
    weight = 20
 