baseURL = "https://jbarkhan.github.io/"
languageCode = "en-us"
title = "Hello"
theme = "paper"
enableInlineShortcodes = true
enableMath = true

[params]
  color = "light"
  github = "github.com/jbarkhan"
  name = "Jerome Barkhan"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

 